### ISSUE TITLE
exposing copy is not safe

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-datatype#48]
The default parameter values generate order dependent artificial fields.
This is not going to be safe if the user inserts field in the middle of the list.

@dwijnand might have example for this.

**Comment by dwijnand** [comment]
## Given

```scala
class A; object A1 extends A
class B; object B1 extends B; object B2 extends B
class C; object C1 extends C

object T {
  def t = {
    val x = new Foo(A1, B1)
    x.copy(b = B2)
  }
}
```

## When the initial Foo (v1) is defined as:

```scala
final class Foo(a: A, b: B) {
  def copy(a: A =a , b: B = b) = new Foo(a, b)
}
```

## Then the final bytecode contains these:

```scala
def copy(a: A, b: B): Foo = new Foo(a, b);
<synthetic> def copy$default$1(): A = Foo.this.a;
<synthetic> def copy$default$2(): B = Foo.this.b;
```

## When you add a parameter at the front and overload:

```scala
final class Foo(c: C, a: A, b: B) {
  def this(a: A, b: B) = this(C1, a, b)
  def copy(a: A, b: B) = new Foo(a, b)
  def copy(c: C = c, a: A = a , b: B = b) = new Foo(c, a, b)
}
```

## Then you get:

```scala
<synthetic> def copy$default$1(): C = Foo.this.c;
<synthetic> def copy$default$2(): A = Foo.this.a;
<synthetic> def copy$default$3(): B = Foo.this.b;

def t(): Foo = {
  val x: Foo = new Foo(A1, B1);
  {
    <artifact> val x$1: B2.type = B2;
    <artifact> val x$2: C = x.copy$default$1();
    <artifact> val x$3: A = x.copy$default$2();
    x.copy(x$2, x$3, x$1)
  }
};
```

## Note

`copy$default$1` has a new, completely incompatible type. This would fail MiMa, it would fail with a `ClassCastException` at runtime (or some other fatal error), and requires a recompilation to fix.

**Comment by dwijnand** [comment]
I checked, and my assumption was wrong: MiMa doesn't fail.. Opened https://github.com/typesafehub/migration-manager/issues/136
