### ISSUE TITLE
Default Arguments vs Interspersed Growth (Design Decision)

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt-datatype#49]
While reviewing #44 @eed3si9n noted that the use of default arguments (in the companion object's `apply`, the constructor, and the `copy` method) moves the default value to the call-site, where it can't be changed in a later version of sbt when we (eg) flip the default from `false` to `true`.

Turns out (I didn't know this) that default arguments are encoded at the definition site as (for instance) `copy$default$1`.

This makes the order of parameters significant, whereby adding a property other than the end can easily cause binary incompatibilities. Thus @eed3si9n opened #48.

The design decision to make is whether to:

1. Allow the use of default arguments, but require properties to be added to the end
2. Allow properties to be added anywhere l, but forgo the use of default arguments and therefore the copy method and requiring abundant use of the withXYZ methods for non-required parameters, even on first construction.

To help evaluating this decision I'm going to rework my patch sbt/librarymanagement#55, with a build of sbt-datatype that doesn't use default arguments, so we can see the diff.

**Comment by dwijnand** [comment]
Diff of approaches: https://github.com/dwijnand/sbt-lm/compare/datatype-sjson-new-and-vectors...sans-default-arguments

**Comment by eed3si9n** [comment]
The point of re-inventing case class is to buy ourselves long-term flexibility and maintainability.
I see default parameter restriction to be a burdensome shackle beyond just the usage of sbt.
For the first construction, we should provide sensible overloads of `appy(...)`

**Comment by dwijnand** [comment]
@eed3si9n 

> For the first construction, we should provide sensible overloads of appy(...)

So you're happy to keep that part of #44?

**Comment by eed3si9n** [comment]
> So you're happy to keep that part of #44?

Not if it uses default parameters.
